import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { Template } from '@/components/templates/template';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Template />
        <h1>
          Welcome to
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h2>
          <Link href="/dummy">
            <a href="replace">Go User Detail Page</a>
          </Link>
        </h2>
      </main>

      <footer>Powered by asamin&sgya</footer>
    </div>
  );
};

export default Home;
