import type { NextPage } from 'next';
import Head from 'next/head';
import { Template } from '@/components/templates/template';

const DummyPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Template />
        <h1>Welcome to Dummy Page!</h1>
      </main>

      <footer>Powered by asamin</footer>
    </div>
  );
};

export default DummyPage;
